### ISSUE TITLE
Can you adapt the latest version of redmine?

### ISSUE THREAD

**Issue by chinatochen** [abahgat/redmine_didyoumean#105]

**Comment by abahgat** [comment]
I haven't used Redmine in a long time and haven't had a chance to understand what the gap is. I can try to take a look in the next several weeks, but can't promise I'll get to the bottom of it soon.

If you have time to send a pull request, I'll be happy to review it!

**Comment by col-panic** [comment]
Trying to active in redmine 5.1 (viahttps://hub.docker.com/_/redmine tag 5.1)i found the following issues:

The mysql2 bundle does not compile anymore (see **MYSQL**), as I use postgres I simply uncommented the
respective lines from Gemfile. A new start mentioned a broken RAKE dependency (see RAKE).

Updating the Gemfile to 
```
source 'https://rubygems.org'

gem 'rake', '~> 13.1.0'
gem 'thinking-sphinx', '~> 3.1.1'
# The MySQL gems mentioned are required for connecting to Sphinx
#gem "mysql2", "~> 0.3.11", :platforms => [:mri, :mingw]
#gem "activerecord-jdbcmysql-adapter", :platforms => :jruby

group :development, :test do
  gem 'awesome_print'
  gem 'hirb'
  gem 'pry'
end
```

ended in

```
rake aborted!
LoadError: cannot load such file -- mysql2 (LoadError)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx.rb:6:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/thinking-sphinx-3.1.4/lib/thinking-sphinx.rb:1:in `<top (required)>'
/usr/src/redmine/config/application.rb:18:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/usr/src/redmine/Rakefile:5:in `<top (required)>'
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

which is a pity - as I don't need mysql anyways! Would be great to fix this plugin for 5.1! 


**RAKE**:
```
rake aborted!
Gem::LoadError: You have already activated rake 13.1.0, but your Gemfile requires rake 12.3.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/usr/src/redmine/config/boot.rb:6:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/usr/src/redmine/config/application.rb:3:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/usr/src/redmine/Rakefile:5:in `<top (required)>'
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
exit code: 1
```


**MYSQL**:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/mysql2-0.3.21/ext/mysql2
/usr/local/bin/ruby extconf.rb
checking for ruby/thread.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-ruby-dir
	--without-ruby-dir
	--with-ruby-include
	--without-ruby-include=${ruby-dir}/include
	--with-ruby-lib
	--without-ruby-lib=${ruby-dir}/lib
/usr/local/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.

	from /usr/local/lib/ruby/3.2.0/mkmf.rb:616:in `block in try_compile'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:565:in `with_werror'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:616:in `try_compile'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:1157:in `block in have_header'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:989:in `block in checking_for'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:354:in `block (2 levels) in postpone'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:324:in `open'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:354:in `block in postpone'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:324:in `open'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:350:in `postpone'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:988:in `checking_for'
	from /usr/local/lib/ruby/3.2.0/mkmf.rb:1156:in `have_header'
	from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /usr/local/bundle/extensions/x86_64-linux/3.2.0/mysql2-0.3.21/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/mysql2-0.3.21 for
inspection.
Results logged to
/usr/local/bundle/extensions/x86_64-linux/3.2.0/mysql2-0.3.21/gem_make.out

  /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
  /usr/local/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
/usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in
build_extensions'
  /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
  /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
  /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:846:in `build_extensions'
/usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
  /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/source/rubygems.rb:202:in `install'
  /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
/usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in
`do_install'
/usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in
`block in worker_pool'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
/usr/local/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in
create_threads'

An error occurred while installing mysql2 (0.3.21), and Bundler cannot continue.

In Gemfile:
  mysql2
exit code: 5
```
